version: "3"
services:
  line:
    container_name: express
    build:
      context: ./
      dockerfile: Dockerfile
    image: adnanrahic/express-docker-app
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: d-baze.me_frontend
